includes:
- configs/SPICE/iodine/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/SPICE_labels/mace_off_large_SpiceIodine

model:
  use_teacher_node_embeddings: True
  emb_size_teacher: 224

outputs:
  final_node_features:
    irrep_dim: 0
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True
  edge_index:
    level: system
    train_on_free_atoms: False
    eval_on_free_atoms: False

loss_functions:
  - final_node_features:
      fn: ark
      coefficient: 1
  - energy:
      fn: per_atom_mae
      coefficient: 5
      reduction: 
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

evaluation_metrics:
  metrics:
    energy:
      - per_atom_mae
    forces:
      - mae
  primary_metric: forces_mae

optim:
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 5
  final_node_distill: True
