trainer: ocp

dataset:

  # train:
  #   format: oc22_lmdb
  #   src: /DATA/user_scratch/hyukjunlim03/2M/
  #   key_mapping:
  #     y: energy
  #     force: forces
  # val:
  #   src: /DATA/user_scratch/hyukjunlim03/all/val_id/

  train:
    format: ase_db
    src: /DATA/user_scratch/hyukjunlim03/OC25/train/
    a2g_args:
      r_energy: True
      r_forces: True
    keep_in_memory: False
    include_relaxed_energy: False
  val:
    src: /DATA/user_scratch/hyukjunlim03/OC25/val/
    a2g_args:
      r_energy: True
      r_forces: True

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
    prediction_dtype: float32
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True
    prediction_dtype: float32

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
    #   - cosine_similarity
    #   - magnitude_error
    # misc:
    #   - energy_forces_within_threshold
  primary_metric: forces_mae
